### ISSUE TITLE
Configuration failed after update to 2.2

### ISSUE THREAD

**Issue by nuggetz** [palazzem/ha-econnect-alarm#115]
With 2.1 installed PRX128 worked just find but after updating to 2.2 the configuration is stuck on a failed state and doesn't recognize entities anymore. 

Error Message:
500 Internal Server Error Server got himself in trouble.

Trouble-shooting done:
tried to downgrade to 2.1: it worked but i can't arm or disarm anymore.
tried to delete all the previews onfigurations and repositories and tried to fresh install 2.2 again: no luck.

 - Operating System (OS): Linux 22.04 Server
 - Home Assistant version: 2023.11.3 container
 - Last working Home Assistant release (if known): 2023.11.3 with 2.1 pre update

**Comment by palazzem** [comment]
Hello @nuggetz and thanks for reaching out!

It looks like there may be an issue with the new setup we changed lately in the 2.2.0. As you joined our Discord channel, I'm just acknowledging the issue here, while we can keep our conversation in our channel. I'll post an update once we identify the issue.

Thanks again!
