### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by galtamur** [palazzem/ha-econnect-alarm#140]
**Describe the bug**
I downloaded the latest stable version (2.2.1), created the folder in the custom_components folder, restarted HA, but when i tried adding the integration i receive the error message below.

**Error message**
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Expected behavior**
I would expect to complete the integration setup process.

**Additional context**
I am using the release 2024.1.5 of HA Core on Docker.

**To Reproduce**
Just run the configuration flow by adding the integration. I tried to restart HA several times but the result is the same.

**Environment**
 - Operating System (OS): Debian
 - Library version (commit or version number): 2.2.1
 - Home Assistant version: 2024.1.5
 - Last working Home Assistant release (if known):

**Comment by palazzem** [comment]
Hello @galtamur, thanks for reaching out! It looks like there may be some sort of incompatibility that we should investigate. I have a few questions that may help me to identify and resolve the issue:
1. Are there any other errors in your logs as soon as you add the integration? Or is this the only thing that you see in your logs?
2. Can you post a screenshot of the configuration modal so that I can take a look at what is actually rendered when the issue happens?
3. Do you have any plugin or frontend module that may alter how the configuration page may work?
4. What level of debugging do you have enabled by default in your `configurations.yaml`? It is something you may have configured like in this doc page: https://www.home-assistant.io/integrations/logger/

For now let's start with just these questions, then I may need more details to properly address this issue you are experiencing. In the meantime, thank you very much for all the time you are spending in providing your feedback!

**Comment by galtamur** [comment]
Hello Emanuele,

first of all let me thank you for your support.

 

Here are the answers to your questions.

1.	When I try adding the integration, this is what is appearing in the log:
2024-02-09 18:32:19.756 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration econnect_metronet: cannot import name 'ParseError' from 'elmo.api.exceptions' (/usr/local/lib/python3.11/site-packages/elmo/api/exceptions.py)
2.	Here is the screenshot:

3.	I suspect the problem may be connected to the fact that I already have the old econnect_alarm integration (https://github.com/palazzem/core/pull/1)
4.	In configuration.yaml I have:
logger:
  default: warning

 

Ciao!

**Comment by palazzem** [comment]
Got it! I think the issue is that you should do a full clean-up of the integration as the version you were using is too old and not compatible with the latest changes (meaning it will go in conflict). Try the following steps:
1. From Home Assistant, go to Settings > Devices & Services > e-Connect/Metronet Alarm > remove the integration:
<img width="1113" alt="image" src="https://github.com/palazzem/ha-econnect-alarm/assets/1560405/7b670d92-3f0b-4b8e-a937-4800d070b7dc">

2. You must repeat the same step for the integration you installed a while ago that should be called "E-connect Alarm" or "Elmo". Basically, no integrations for the alarm should be installed at this step.
3. As you were using an old integration (0.3.0 vs 2.2.1), you should remove all widgets you created in the Home Assistant Lovelace dashboard, as one year ago we had to make some breaking changes to improve the integration quality (an unwanted but needed change).
4. From Settings > Devices & Services > Entities, filter the list by `econnect` and remove all entities that belong to the econnect integration. Repeat the same process filtering by `elmo` too, as you may still have some entities in the database:
<img width="1217" alt="image" src="https://github.com/palazzem/ha-econnect-alarm/assets/1560405/8c5737c7-6ffb-4816-81b7-e560d8d35e55">

5. As you are using Docker, your configuration should be mounted from a folder where you store the `configurations.yaml`. Open the `custom_components` folder and delete **ONLY** the folders related to the e-Connect integration. Theoretically, you should have 1 or 2 folders to delete only.
6. Double check your `configurations.yaml`, and be sure that no entries related to the integration are present. If they are, just delete them.
7. Restart Home Assistant and when it's loaded, be sure you can't install any e-Connect integration (try to add it, you should not find them in the list).
8. Install the 2.2.1 version as you usually do: https://github.com/palazzem/ha-econnect-alarm/releases/tag/v2.2.1.
9. Restart Home Assistant.
10. At this point you should have a fresh setup, and you should be able to install properly the latest version.

This process involves multiple DELETE steps. If you are unsure, just stop and ask me for clarifications as if you don't delete the right folder, you may break your Home Assistant installation. Also, instead of doings steps 8-10, you may evaluate to install https://hacs.xyz/ that will make upgrades way easier for you.

Hope this helps! If something doesn't work, write me all the steps you did up to that point, so I can continue helping you from there! Feel free to join our [Discord channel](https://discord.gg/NSmAPWw8tE) if you want to get a broader help from our community (first language of choice in the channel is Italian)!

**Comment by galtamur** [comment]
Thak you Emanuele for the very detailed instructions!

I will try doing the job in the coming days.

 

Have a great day.

 

GA

**Comment by palazzem** [comment]
Hello @galtamur ! I'm wondering if you had a chance to try a clean installation, and if it helped solving the problem! Let us know if there is anything we can do to better support you!

**Comment by galtamur** [comment]
Ciao Emanuele, thank you for asking but no, I’ve been in Cervinia the whole week skiing 😀
Maybe I will have time the next weekend.
Ciao!

Giuliano Altamura
via Sant’Elia 14
22070 Casnate con Bernate (CO)

**Comment by palazzem** [comment]
Hahaha no worries! Take your time and feel free to update us whenever you'll try these changes!

Enjoy!

**Comment by palazzem** [comment]
Hello @galtamur ! I'm closing the issue as it has been stale for a while! But feel free to re-open it if you think you need further assistance!

**Comment by galtamur** [comment]
Hi Emanuele: I managed to upgrade successfully to the new integration.

Thanks a lot for your support!

 

GA
