### ISSUE TITLE
Unable to install version 2.0.1 through HACS

### ISSUE THREAD

**Issue by AndreaMagis** [palazzem/ha-econnect-alarm#77]
I have installed the latest HA and integration updates, the insertion status has not been automatically updated for about 2 weeks. 
The integration communicates: I can activate and deactivate from HA, but if I deactivate or activate with mobile app or key, the new state does not appear in HA, the previous one remains. 
If I reboot HA, everything is synced to the correct state upon reboot. 
What can it be?

**Comment by palazzem** [comment]
Hello @AndreaMagis and thanks for reaching out!

This issue seems something that has been reported by another user (#51) and it looks like it has been addressed in the latest version of the integration. The latest version is 2.0.1 that has been released a few hours ago, so it's possible you are still using the 2.0.0 that has this bug.

Can you confirm you are running the version 2.0.1? If you want to be 100% sure, I would recommend these steps:
1. Uninstall the integration from HA (https://<HA_IP>/config/integrations/integration/econnect_metronet) and then click the three dots and click "delete"
2. Remove `econnect_metronet` folder from your `custom_components` directory.
3. Download the tar or zip file available in the 2.0.1 release note: https://github.com/palazzem/ha-econnect-alarm/releases/tag/v2.0.1
4. Extract the archive and move only the `econnect_metronet` folder inside `custom_components`
5. Restart HA
6. Reinstall the integration

In case you are using HACS, you can add this repository (https://github.com/palazzem/ha-econnect-alarm) as a custom repository, and force the download of version 2.0.1. In any case, once you install the new version, you have to restart HA and not just the integration.

Let us know if the 2.0.1 solves the issue! Thank you so much!

**Comment by AndreaMagis** [comment]
I use the latest version 2.0.1 but the problem doesn't seem to be solved. The status does not update. I tried reloading the integration without restarting HA and the status updated after reloading. If I don't intervene, it won't update

Il you want I test news, I’m italian

**Comment by palazzem** [comment]
Allora possiamo anche parlare anche in italiano! Dunque, la versione 2.0.1 è stata rilasciata questa notte, quindi dopo che hai fatto l'upgrade questa mattina, il problema ti si è subito verificato entro quanto?

Per fare le prove, dovresti installare questa versione di sviluppo che aggiunge dei log specifici per identificare il blocco: https://github.com/palazzem/ha-econnect-alarm/releases/tag/v2.0.1.dev1

Usa le indicazioni del messaggio precedente per installare questa versione che non appena si verificherà il problema andrà a darci ulteriori indicazioni.

Dopo averla installata e riconfigurata, dovresti attivare i log di debug aggiungendo al tuo `configuration.yaml` la seguente configurazione (o modifica la tua esistente se ce l'hai già):
```
logger:
  default: error
  logs:
    custom_components.econnect_metronet: debug
```

A quel punto, l'integrazione funzionerà e non appena si verificherà il problema puoi estrarre i log ed inviarceli. Se vuoi, puoi unirti al canale Discord dove potrebbe essere più facile restare in contatto: https://discord.gg/NSmAPWw8tE

Tienimi aggiornato non appena installi la versione di sviluppo ed attivi il debug di log.

**Comment by palazzem** [comment]
After working with @AndreaMagis over Discord, we identified that HACS wasn't properly installing the 2.0.1 as the integration was correctly downloaded, but the previous one has not been removed. This created a clash between an old version and a new version that is now addressed. The integration is working as expected.

That said, before closing this issue, I want to keep open a task where we add a DEBUG log that writes what is the integration version. This is really important as it's critical to understand if the version has been installed correctly.

Also the `econnect-python` version must be available.

**Comment by palazzem** [comment]
With a further investigation, it looks like there is a HACS limitation in what assets you can release. If any asset other than the one used in HACS is present, HACS tries to download all of them creating downloading/installation issues.

This was a second issue experienced by the user, and it's kept track on https://github.com/palazzem/ha-econnect-alarm/issues/75.
